import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.churchBranches.deleteMany({})
  await prisma.churchBranches.createMany({
    data: [
      { name: 'Abolição' },
      { name: 'Afonso Pena' },
      { name: 'Água Branca' },
      { name: 'Alameda Paulista' },
      { name: 'Aldeia da Serra' },
      { name: 'Alto da Lapa' },
      { name: 'Alto das Mercês' },
      { name: 'Alto dos Pinheiros' },
      { name: 'Alto Vera Cruz' },
      { name: 'Alvorada' },
      { name: 'Amparo ' },
      { name: 'Anil' },
      { name: 'Arcos' },
      { name: 'Areal ' },
      { name: 'Aureny IV' },
      { name: 'Bady Bassit' },
      { name: 'Bairro Alto ' },
      { name: 'Bairro Amambaí' },
      { name: 'Bairro Aviário' },
      { name: 'Bairro Belvedere' },
      { name: 'Bairro Botafogo' },
      { name: 'Bairro Brasília' },
      { name: 'Bairro Carrilho' },
      { name: 'Bairro Cidade Industrial' },
      { name: 'Bairro Colégio' },
      { name: 'Bairro da Fátima' },
      { name: 'Bairro da Ilha' },
      { name: 'Bairro Diamante' },
      { name: 'Bairro do Divino' },
      { name: 'Bairro do Limão' },
      { name: 'Bairro do Óleo' },
      { name: 'Bairro dos Estados' },
      { name: 'Bairro Imperial' },
      { name: 'Bairro Industrial' },
      { name: 'Bairro Julia Kubstchek' },
      { name: 'Bairro Nacional' },
      { name: 'Bairro Nazaré' },
      { name: 'Bairro Novo' },
      { name: 'Bairro Paraíso' },
      { name: 'Bairro Santo Elias' },
      { name: 'Bairro Varginha' },
      { name: 'Bairro Veneza' },
      { name: 'Bancários' },
      { name: 'Bandeirantes' },
      { name: 'Bariri' },
      { name: 'Barra do Mendes' },
      { name: 'Barreirinha' },
      { name: 'Barreiros' },
      { name: 'Barreto' },
      { name: 'Barro' },
      { name: 'Bela Aurora' },
      { name: 'Bela Vista' },
      { name: 'Boa Vista' },
      { name: 'Bom Jesus da Lapa' },
      { name: 'Bom Retiro' },
      { name: 'Boqueirão' },
      { name: 'Bosque da Saúde' },
      { name: 'Bosque' },
      { name: 'Bosques' },
      { name: 'Bracuhy' },
      { name: 'Brasil de Tailândia Pará' },
      { name: 'Brasil em Anicuns' },
      { name: 'Brasil em Confresa' },
      { name: 'Brasil Morada da Lua' },
      { name: 'Braz' },
      { name: 'Bugre' },
      { name: 'Buritis' },
      { name: 'Cabral' },
      { name: 'Cachoeira' },
      { name: 'Caçote' },
      { name: 'Caetés 1' },
      { name: 'Cafarnaum' },
      { name: 'Caiçara' },
      { name: 'Cajazeiras' },
      { name: 'Caju' },
      { name: 'Calvário' },
      { name: 'Cambeba' },
      { name: 'Caminho' },
      { name: 'Campo Belo' },
      { name: 'Campo Grande' },
      { name: 'Campo Largo' },
      { name: 'Campo Verde' },
      { name: 'Canaã dos Carajás' },
      { name: 'Cariacica Sede' },
      { name: 'Carnaubal' },
      { name: 'Carumbu' },
      { name: 'Carvão' },
      { name: 'Casa Forte' },
      { name: 'Catarcione' },
      { name: 'Catonho' },
      { name: 'Cedro' },
      { name: 'Cedro' },
      { name: 'Celula Mater' },
      { name: 'Centenário em Lajinha' },
      { name: 'Centenário' },
      { name: 'Central' },
      { name: 'Cerâmica' },
      { name: 'Céu Azul' },
      { name: 'Champagnat' },
      { name: 'Chapéu' },
      { name: 'Cidade de Prata' },
      { name: 'Cidade Líder' },
      { name: 'Cidade Operária' },
      { name: 'Cidade Praiana' },
      { name: 'Coelho da Rocha' },
      { name: 'Coelho' },
      { name: 'Conceição da Barra' },
      { name: 'Conceição de Ipanema' },
      { name: 'Conceição de Jacareí' },
      { name: 'Conceição do Araguaia' },
      { name: 'Cônego' },
      { name: 'Conquista' },
      { name: 'Contorno Sul' },
      { name: 'Costa Marques' },
      { name: 'CPA III' },
      { name: 'Crespo' },
      { name: 'Cristo' },
      { name: 'Cruz do Espírito Santo' },
      { name: 'Distrito de Rive' },
      { name: 'Divino' },
      { name: 'Divinolândia de Minas' },
      { name: 'Doulos' },
      { name: 'Durval de Barros' },
      { name: 'Ebenézer - Uberlândia' },
      { name: 'Ebenézer de Americana' },
      { name: 'Ebenézer de Campinas' },
      { name: 'Ebenézer de São Carlos' },
      { name: 'Ebenézer de São Paulo' },
      { name: 'Ebenézer de Vargem Grande' },
      { name: 'Ebenézer em Jardim Bom Pastor' },
      { name: 'Ebenézer em Russas' },
      { name: 'Ebenézer no Bairro Bethânia' },
      { name: 'Ebenezer' },
      { name: 'Ebenézer' },
      { name: 'Eldorado dos Carajás' },
      { name: 'Elvamar' },
      { name: 'Emanuel' },
      { name: 'Emaús' },
      { name: 'Encontro Vinho Novo' },
      { name: 'Érico Cardoso' },
      { name: 'Ermelino Matarazzo' },
      { name: 'Esmirna' },
      { name: 'Espaço de Vida' },
      { name: 'Esperança' },
      { name: 'Estância' },
      { name: 'Estreito' },
      { name: 'Farol' },
      { name: 'Fazenda Rio Grande' },
      { name: 'Fazendinha' },
      { name: 'Feira da Mata' },
      { name: 'Feliz Natal' },
      { name: 'Filadélfia ' },
      { name: 'Filadélfia ' },
      { name: 'Filadélfia da Rua da Palha' },
      { name: 'Filadélfia de Americana' },
      { name: 'Filadélfia de Aracaju' },
      { name: 'Filadélfia de Ariquemes' },
      { name: 'Filadélfia de Boquim' },
      { name: 'Filadélfia de Cristinápolis' },
      { name: 'Filadélfia de Estância' },
      { name: 'Filadélfia de Franca' },
      { name: 'Filadélfia de Marília' },
      { name: 'Filadélfia de Patrocínio' },
      { name: 'Filadélfia de São Carlos ' },
      { name: 'Filadélfia de Tobias Barreto' },
      { name: 'Filadélfia de Umbaúba' },
      { name: 'Filadélfia GV' },
      { name: 'Filadélfia Tapera da Serra' },
      { name: 'Filadélfia' },
      { name: 'Filadélfia' },
      { name: 'Filadélfia' },
      { name: 'Finsocial' },
      { name: 'Flávio Marques Lisboa' },
      { name: 'Flor de Maio' },
      { name: 'Floramar' },
      { name: 'Florença' },
      { name: 'Floresta de Governador Valadares' },
      { name: 'Floresta' },
      { name: 'Floresta' },
      { name: 'Fonte de Vida' },
      { name: 'Fontinha' },
      { name: 'Formiga' },
      { name: 'Formosa' },
      { name: 'Formoso' },
      { name: 'Frade' },
      { name: 'Frutilândia' },
      { name: 'Galpão 3.16' },
      { name: 'Geisel' },
      { name: 'Geribá ' },
      { name: 'Getsêmani de Guarulhos' },
      { name: 'Getsêmani em Parque Paulista' },
      { name: 'Getsêmani' },
      { name: 'Gileade de Guarulhos' },
      { name: 'Gileade' },
      { name: 'Glória' },
      { name: 'Goiabeiras' },
      { name: 'Goianésia do Pará' },
      { name: 'Graça e Vida' },
      { name: 'Graça' },
      { name: 'Grã-Duquesa' },
      { name: 'Grajaú' },
      { name: 'Guabirotuba' },
      { name: 'Guanabara' },
      { name: 'Guanambi' },
      { name: 'Guapimirim' },
      { name: 'Guará II' },
      { name: 'Guará' },
      { name: 'Guaraná' },
      { name: 'Guaripocaba' },
      { name: 'Guarus' },
      { name: 'Hauer' },
      { name: 'Hebrom' },
      { name: 'Humaitá ' },
      { name: 'Humaitá' },
      { name: 'Iawé Nissi' },
      { name: 'IBC' },
      { name: 'Ibura' },
      { name: 'Icém' },
      { name: 'Ideal' },
      { name: 'Igreja Presbiterina Comunidade Viva' },
      { name: 'Igreja Presbiterina de Planalto' },
      { name: 'Igreja Venda Nova do Imigrante' },
      { name: 'Iguaçu' },
      { name: 'Independência' },
      { name: 'Ingleses' },
      { name: 'Integral' },
      { name: 'Ipatinga' },
      { name: 'Ipiranga' },
      { name: 'Ipiranga' },
      { name: 'Irecê' },
      { name: 'Itabirito' },
      { name: 'Itaboraí' },
      { name: 'Itaici Município de Municeire' },
      { name: 'Itanhandu' },
      { name: 'Itapemirim' },
      { name: 'Itaporanga' },
      { name: 'Itaquera II' },
      { name: 'Itatiaia' },
      { name: 'IV Centenário' },
      { name: 'IV Centenário' },
      { name: 'Jabaquara' },
      { name: 'Jaburuna' },
      { name: 'Jacarepaguá' },
      { name: 'Jacintinho' },
      { name: 'Janga' },
      { name: 'Jaó' },
      { name: 'Jaqueline' },
      { name: 'Jaraguá' },
      { name: 'Jardim  ABC' },
      { name: 'Jardim 13 de Maio' },
      { name: 'Jardim Acácio' },
      { name: 'Jardim Aeroporto' },
      { name: 'Jardim Alto Paraíso' },
      { name: 'Jardim Alvorada' },
      { name: 'Jardim Amarantina' },
      { name: 'Jardim América' },
      { name: 'Jardim Apurá' },
      { name: 'Jardim Aristocrata' },
      { name: 'Jardim Arpoador' },
      { name: 'Jardim Atlântico' },
      { name: 'Jardim Augusta' },
      { name: 'Jardim Bandeirantes' },
      { name: 'Jardim Bela Vista' },
      { name: 'Jardim Bom Pastor' },
      { name: 'Jardim Bonfiglioli' },
      { name: 'Jardim Botânico' },
      { name: 'Jardim Califórnia' },
      { name: 'Jardim Camburi' },
      { name: 'Jardim Campos' },
      { name: 'Jardim Canaã' },
      { name: 'Jardim Canadá' },
      { name: 'Jardim Carvalho' },
      { name: 'Jardim Castelo' },
      { name: 'Jardim Cavinato' },
      { name: 'Jardim Colorado' },
      { name: 'Jardim Conceição' },
      { name: 'Jardim D’Abril' },
      { name: 'Jardim da Glória' },
      { name: 'Jardim da Penha' },
      { name: 'Jardim Damasceno' },
      { name: 'Jardim das Américas' },
      { name: 'Jardim Das Oliveiras de Leme' },
      { name: 'Jardim Das Oliveiras' },
      { name: 'Jardim das Oliveiras' },
      { name: 'Jardim Das Oliveiras' },
      { name: 'Jardim de Oração' },
      { name: 'Jardim do Aeroporto' },
      { name: 'Jardim Elba' },
      { name: 'Jardim Esmeraldina' },
      { name: 'Jardim Esperança' },
      { name: 'Jardim Fátima' },
      { name: 'Jardim Flamboyant' },
      { name: 'Jardim Fontalis' },
      { name: 'Jardim Garcia' },
      { name: 'Jardim Girassol' },
      { name: 'Jardim Goiás' },
      { name: 'Jardim Guanabara' },
      { name: 'Jardim Guaraituba' },
      { name: 'Jardim Helian' },
      { name: 'Jardim Imperial' },
      { name: 'Jardim Imperial' },
      { name: 'Jardim Ipanema ' },
      { name: 'Jardim Ipê' },
      { name: 'Jardim Ipiranga' },
      { name: 'Jardim Itália' },
      { name: 'Jardim Itália' },
      { name: 'Jardim Itapuan' },
      { name: 'Jardim Jerusalém' },
      { name: 'Jardim Laguna' },
      { name: 'Jardim Licínia' },
      { name: 'Jardim Magnólias' },
      { name: 'Jardim Maguary' },
      { name: 'Jardim Marilene' },
      { name: 'Jardim Maringá' },
      { name: 'Jardim Medina' },
      { name: 'Jardim Metrópole' },
      { name: 'Jardim Monções' },
      { name: 'Jardim Monte Alegre' },
      { name: 'Jardim Monza' },
      { name: 'Jardim Morada do Sol' },
      { name: 'Jardim Mutinga' },
      { name: 'Jardim Novo Mundo' },
      { name: 'Jardim Palmeiras' },
      { name: 'Jardim Paraíso' },
      { name: 'Jardim Paraíso' },
      { name: 'Jardim Paulista' },
      { name: 'Jardim Pedro José Nunes' },
      { name: 'Jardim Pérola' },
      { name: 'Jardim Petrópolis' },
      { name: 'Jardim Planalto de Passos' },
      { name: 'Jardim Planalto' },
      { name: 'Jardim Raquel' },
      { name: 'Jardim Rincão' },
      { name: 'Jardim Santana' },
      { name: 'Jardim Santiago' },
      { name: 'Jardim São Francisco' },
      { name: 'Jardim São Geraldo' },
      { name: 'Jardim São Paulo' },
      { name: 'Jardim São Vicente' },
      { name: 'Jardim Satélite' },
      { name: 'Jardim Sorriso' },
      { name: 'Jardim Sul' },
      { name: 'Jardim Tangará' },
      { name: 'Jardim Tatiane' },
      { name: 'Jardim Teresópolis' },
      { name: 'Jardim Tranquilidade' },
      { name: 'Jardim Tropical' },
      { name: 'Jardim Uchoa' },
      { name: 'Jardim Ulisses' },
      { name: 'Jardim Universitário' },
      { name: 'Jardim Vista Alegre' },
      { name: 'Jardim Vitoria' },
      { name: 'Jardim Vitória' },
      { name: 'Jardim' },
      { name: 'Jardins Mangueiral' },
      { name: 'Jardins' },
      { name: 'Jardins' },
      { name: 'Jequitibá' },
      { name: 'Jiribatuba ' },
      { name: 'João de Deus' },
      { name: 'João Dourado' },
      { name: 'João Neiva' },
      { name: 'Jockey Club' },
      { name: 'Jockey' },
      { name: 'José Américo' },
      { name: 'José de Anchieta' },
      { name: 'José Manoel da Conceição - JMC' },
      { name: 'José Pedro' },
      { name: 'José Walter' },
      { name: 'Juazeiro do Norte' },
      { name: 'Jundiaí' },
      { name: 'Kadosh' },
      { name: 'Kairós' },
      { name: 'Kátia' },
      { name: 'Lagarto' },
      { name: 'Lago Azul' },
      { name: 'Lago Norte' },
      { name: 'Lago Sul' },
      { name: 'Lagoa da Prata' },
      { name: 'Largo da Paz' },
      { name: 'Limoeiro ' },
      { name: 'Lírio dos Vales' },
      { name: 'Louvor' },
      { name: 'Luís Eduardo Magalhães' },
      { name: 'Luz da Alvorada' },
      { name: 'Luz do Mundo' },
      { name: 'Luz do Vale' },
      { name: 'Luz e Vida' },
      { name: 'Luz no Vale' },
      { name: 'Luz' },
      { name: 'Maanaim' },
      { name: 'Macedônia' },
      { name: 'Macedônia' },
      { name: 'Manancial de Leme' },
      { name: 'Manancial de Natal' },
      { name: 'Manancial Vespasiano' },
      { name: 'Manancial' },
      { name: 'Mandacaru' },
      { name: 'Mangabeira II' },
      { name: 'Maracanã' },
      { name: 'Maranata' },
      { name: 'Maranatha' },
      { name: 'Maranguape II' },
      { name: 'Marapé (Manancial)' },
      { name: 'Marback' },
      { name: 'Marechal Hermes' },
      { name: 'Maria Mendonça' },
      { name: 'Mariléia ' },
      { name: 'Matupá' },
      { name: 'Méier' },
      { name: 'Memorial da Barra' },
      { name: 'Memorial da Vila Cardeal' },
      { name: 'Memorial de Natal' },
      { name: 'Memorial de São Paulo' },
      { name: 'Memorial do Curado I' },
      { name: 'Memorial do Curado IV' },
      { name: 'Memorial' },
      { name: 'Metropolitana de Alphaville' },
      { name: 'Metropolitana de BH em Mangabeiras' },
      { name: 'Metropolitana de Guarulhos' },
      { name: 'Metropolitana de Porto Alegre' },
      { name: 'Metropolitana de São Paulo' },
      { name: 'Metropolitana do Stiep' },
      { name: 'Mogi das Cruzes' },
      { name: 'Monnerat' },
      { name: 'Monte das Oliveiras' },
      { name: 'Monte Hermom' },
      { name: 'Monte Horebe da Figueira' },
      { name: 'Monte Horebe' },
      { name: 'Monte Moriá' },
      { name: 'Monte Moriah' },
      { name: 'Monte Sião do Jardim Brasil' },
      { name: 'Monte Sião' },
      { name: 'Monte Sinai' },
      { name: 'Montes Belos' },
      { name: 'Morada das Árvores ' },
      { name: 'Morada de Laranjeiras' },
      { name: 'Morada do Ouro' },
      { name: 'Morada Nova' },
      { name: 'Moreno' },
      { name: 'Moria' },
      { name: 'Moriá' },
      { name: 'Moriah' },
      { name: 'Morumbi Sul' },
      { name: 'Morumbi' },
      { name: 'Mosaico ' },
      { name: 'Muarama' },
      { name: 'Mundo Novo' },
      { name: 'Mutum' },
      { name: 'Nacional' },
      { name: 'Nioaque' },
      { name: 'Nossa Casa' },
      { name: 'Nossa Senhora da Glória' },
      { name: 'Nova Aliança' },
      { name: 'Nova Andradina' },
      { name: 'Nova Betânia de Mossoró' },
      { name: 'Nova Bethania' },
      { name: 'Nova Canaã' },
      { name: 'Nova Cidade' },
      { name: 'Nova Dourados' },
      { name: 'Nova Esperança' },
      { name: 'Nova Jerusalém ' },
      { name: 'Nova Jerusalém em Esmeraldas' },
      { name: 'Nova Jerusalém' },
      { name: 'Nova Jerusalém' },
      { name: 'Nova Marabá' },
      { name: 'Nova Palestina' },
      { name: 'Nova Redenção' },
      { name: 'Nova Serrana' },
      { name: 'Nova União' },
      { name: 'Nova Vida' },
      { name: 'Nova Vista' },
      { name: 'Nova' },
      { name: 'Nove de Abril' },
      { name: 'Novo Angelim' },
      { name: 'Novo Caminho' },
      { name: 'Novo Gama' },
      { name: 'Novo Horizonte' },
      { name: 'Novo Mundo' },
      { name: 'Novo Parque' },
      { name: 'Novo Tempo' },
      { name: 'Olaria' },
      { name: 'Oriente' },
      { name: 'Orvalho do Hermom' },
      { name: 'Padre Eustáquio' },
      { name: 'Paiol' },
      { name: 'Palmares' },
      { name: 'Palmas-Sul ' },
      { name: 'Palmeira dos Indios' },
      { name: 'Paraíso' },
      { name: 'Paramirim' },
      { name: 'Paranatinga' },
      { name: 'Paraty' },
      { name: 'Parque Aeroporto' },
      { name: 'Parque Americano' },
      { name: 'Parque Araruama' },
      { name: 'Parque Aurora' },
      { name: 'Parque Bandeirantes' },
      { name: 'Parque Boturussu' },
      { name: 'Parque Capibaribe' },
      { name: 'Parque das Américas' },
      { name: 'Parque das Bandeiras' },
      { name: 'Parque Das Laranjeiras' },
      { name: 'Parque das Laranjeiras' },
      { name: 'Parque das Nações' },
      { name: 'Parque do Carmo' },
      { name: 'Parque do Tietê' },
      { name: 'Parque dos Eucaliptos' },
      { name: 'Parque dos Guarus' },
      { name: 'Parque Dourado' },
      { name: 'Parque Erasmo Assunção' },
      { name: 'Parque Iguaçu' },
      { name: 'Parque Industrial' },
      { name: 'Parque Ipê' },
      { name: 'Parque Marilândia' },
      { name: 'Parque Nacional' },
      { name: 'Parque Novo Rio' },
      { name: 'Parque Panorama' },
      { name: 'Parque Real' },
      { name: 'Parque São Domingos' },
      { name: 'Parque São Vicente' },
      { name: 'Parque Selecta' },
      { name: 'Parque Taquaral' },
      { name: 'Parque Xangrilá' },
      { name: 'Paulistana' },
      { name: 'Pé do Galo' },
      { name: 'Pechincha' },
      { name: 'Pedra Viva' },
      { name: 'Pedras Vivas' },
      { name: 'Peniel ' },
      { name: 'Peniel no Retiro' },
      { name: 'Peniel' },
      { name: 'Peniel' },
      { name: 'Pereiro' },
      { name: 'Peró' },
      { name: 'Pina' },
      { name: 'Pioneira de Brasília' },
      { name: 'Pioneira de Gameleira ' },
      { name: 'Pioneira' },
      { name: 'Piracaia' },
      { name: 'Pirangi' },
      { name: 'Placas' },
      { name: 'Planalto' },
      { name: 'Planalto' },
      { name: 'Plenitude' },
      { name: 'Poços' },
      { name: 'Pontes dos Carvalhos' },
      { name: 'Porto Alegre' },
      { name: 'Porto de Santana' },
      { name: 'Porto do Rosa' },
      { name: 'Praça João Pessoa' },
      { name: 'Praia da Bica' },
      { name: 'Praia de Itapoã' },
      { name: 'Praia de Mauá' },
      { name: 'Praia do Canto' },
      { name: 'Praia Sul' },
      { name: 'Primavera' },
      { name: 'Primeiro de Maio' },
      { name: 'Príncipe' },
      { name: 'Propriá' },
      { name: 'Quilombo Mel da Pedreira' },
      { name: 'Raul Soares' },
      { name: 'Real Aliança' },
      { name: 'Realengo' },
      { name: 'Reconciliação' },
      { name: 'Recreio dos Bandeirantes' },
      { name: 'Recreio' },
      { name: 'Redenção' },
      { name: 'Redenção' },
      { name: 'Redentor' },
      { name: 'Região Sul' },
      { name: 'Reina' },
      { name: 'Renascença' },
      { name: 'Renascer em Queimadas' },
      { name: 'Renascer' },
      { name: 'República' },
      { name: 'Residencial Santos Dumont' },
      { name: 'Resplendor' },
      { name: 'Restauração' },
      { name: 'Reviver' },
      { name: 'Riachuelo' },
      { name: 'Ribeirão das Neves ' },
      { name: 'Ribeiro de Abreu' },
      { name: 'Ribeiropolis' },
      { name: 'Rio de Janeiro' },
      { name: 'Rio Doce' },
      { name: 'Rio Muqui' },
      { name: 'Rio Tinto' },
      { name: 'Riviera' },
      { name: 'Rocha Eterna de Sorocaba' },
      { name: 'Rocha Eterna' },
      { name: 'Rolim de Moura' },
      { name: 'Rosa dos Ventos' },
      { name: 'Roseiral' },
      { name: 'Salém' },
      { name: 'Salgado de São Félix' },
      { name: 'Sana' },
      { name: 'Santa Cruz' },
      { name: 'Santa Izabel do Ivaí' },
      { name: 'Santa Lúcia' },
      { name: 'Santa Luzia' },
      { name: 'Santa Margarida' },
      { name: 'Santa Maria de Campos' },
      { name: 'Santa Maria' },
      { name: 'Santa Maria' },
      { name: 'Santa Rita do Passa Quatro' },
      { name: 'Santa Rita do Sapucaí' },
      { name: 'Santa Rita' },
      { name: 'Santana do Araguaia' },
      { name: 'Santana' },
      { name: 'Santarém' },
      { name: 'Santíssimo' },
      { name: 'Santo Aleixo' },
      { name: 'Santo Amaro' },
      { name: 'Santo Anastácio' },
      { name: 'Santo Antônio da Platina' },
      { name: 'Santo Antônio do Jacinto' },
      { name: 'São Bernardo' },
      { name: 'São Borja' },
      { name: 'São Caetano do Sul' },
      { name: 'São Carlos' },
      { name: 'São Félix do Xingu' },
      { name: 'São Fidélis' },
      { name: 'São Francisco do Guaporé ' },
      { name: 'São Francisco do Sul' },
      { name: 'São Gabriel do Oeste' },
      { name: 'São Geraldo do Araguaia' },
      { name: 'São Gonçalo' },
      { name: 'São João Batista do Glória' },
      { name: 'São João da Cristina' },
      { name: 'São João Del Rei' },
      { name: 'São João do Paraíso' },
      { name: 'São Joaquim da Barra' },
      { name: 'São Joaquim' },
      { name: 'São José das Palmeiras ' },
      { name: 'São José Das Torres' },
      { name: 'São José do Belmonte' },
      { name: 'São José do Calçado' },
      { name: 'São José do Ribeirão' },
      { name: 'São José do Rio Pardo' },
      { name: 'São José do Rio Preto' },
      { name: 'São José dos Campos' },
      { name: 'São José dos Pinhais' },
      { name: 'São José' },
      { name: 'São Lourenço' },
      { name: 'São Luis' },
      { name: 'São Mateus' },
      { name: 'São Miguel do Araguaia' },
      { name: 'São Miguel do Guaporé' },
      { name: 'São Miguel Paulista' },
      { name: 'São Miguel' },
      { name: 'São Pedro do Avai' },
      { name: 'São Pedro' },
      { name: 'São Roque' },
      { name: 'São Roque' },
      { name: 'São Sebastião do Paraíso' },
      { name: 'São Sebastião' },
      { name: 'São Vicente' },
      { name: 'Sapé' },
      { name: 'Sapezal' },
      { name: 'Sapiranga' },
      { name: 'Sapopemba' },
      { name: 'Saracuruna' },
      { name: 'Savoy' },
      { name: 'Seabra' },
      { name: 'Segunda em São José' },
      { name: 'Semear' },
      { name: 'Sena Madureira' },
      { name: 'Senador Câmara' },
      { name: 'Senador Guiomard' },
      { name: 'Senges' },
      { name: 'Seropédica' },
      { name: 'Serra da Meruoca' },
      { name: 'Serra do Salitre' },
      { name: 'Serra Monte' },
      { name: 'Serra Negra' },
      { name: 'Serra Negra' },
      { name: 'Serra Talhada' },
      { name: 'Serra' },
      { name: 'Serrana' },
      { name: 'Serrano' },
      { name: 'Serraria' },
      { name: 'Serrolândia' },
      { name: 'Sertaneja' },
      { name: 'Sertânia' },
      { name: 'Setor Bueno' },
      { name: 'Setor de Mansões' },
      { name: 'Setor Leste' },
      { name: 'Setor M Norte' },
      { name: 'Setor Pedro Ludovico' },
      { name: 'Setor Sul' },
      { name: 'Setor Sul' },
      { name: 'Setor Universitário' },
      { name: 'Shalom' },
      { name: 'Shekinah' },
      { name: 'Shekináh' },
      { name: 'Sião ' },
      { name: 'Sião' },
      { name: 'Sião' },
      { name: 'Siloé' },
      { name: 'Simão Dias' },
      { name: 'Simonton' },
      { name: 'Sinai' },
      { name: 'Sinop' },
      { name: 'Sitio da Luz' },
      { name: 'Sitio Novo' },
      { name: 'Sítio Novo' },
      { name: 'Sobral' },
      { name: 'Sobrália' },
      { name: 'Socorro' },
      { name: 'Solânea' },
      { name: 'Solar Park' },
      { name: 'Sorocaba' },
      { name: 'Sorriso' },
      { name: 'Sousa' },
      { name: 'Sousas' },
      { name: 'Souto Soares ' },
      { name: 'Suape' },
      { name: 'Sucupira' },
      { name: 'Sudoeste' },
      { name: 'Sulacap' },
      { name: 'Sumaré' },
      { name: 'Suzano' },
      { name: 'Tabatinga' },
      { name: 'Tabuazeiro' },
      { name: 'Taiobeiras' },
      { name: 'Talhamares' },
      { name: 'Tambaú' },
      { name: 'Tambay' },
      { name: 'Tanabi' },
      { name: 'Tangará da Serra' },
      { name: 'Tanguá' },
      { name: 'Tanque de Betesda' },
      { name: 'Tapera' },
      { name: 'Taquara' },
      { name: 'Taquara' },
      { name: 'Taquaritinga' },
      { name: 'Tarumã' },
      { name: 'Tarumirim' },
      { name: 'Tatuapé' },
      { name: 'Tatuí' },
      { name: 'Tauapé' },
      { name: 'Taubaté' },
      { name: 'Taveirópolis' },
      { name: 'Tefé Esmirina' },
      { name: 'Teixeira de Freitas' },
      { name: 'Tejipió' },
      { name: 'Teodoro Sampaio' },
      { name: 'Teresina' },
      { name: 'Teresópolis' },
      { name: 'Terra Mater' },
      { name: 'Terra Nova' },
      { name: 'Terra Vermelha' },
      { name: 'Thomaz Coelho' },
      { name: 'Tianguá ' },
      { name: 'Tibiri' },
      { name: 'Tietê' },
      { name: 'Tijucal' },
      { name: 'Tijuco Preto ' },
      { name: 'Tijuquinhas' },
      { name: 'Timbaúba' },
      { name: 'Tingidor' },
      { name: 'Tingui' },
      { name: 'Tiradentes' },
      { name: 'Toledo' },
      { name: 'Torre de Pedra' },
      { name: 'Torre' },
      { name: 'Torrelândia' },
      { name: 'Torrinha' },
      { name: 'Travessão da Barra' },
      { name: 'Travessão de Campos' },
      { name: 'Três Corações' },
      { name: 'Três Lagoas' },
      { name: 'Três Riachos' },
      { name: 'Três Rios' },
      { name: 'Treze de Maio' },
      { name: 'Trezentos' },
      { name: 'Tri Campeão' },
      { name: 'Tribobó' },
      { name: 'Trindade' },
      { name: 'Trindade' },
      { name: 'Tubarão' },
      { name: 'Tucurui' },
      { name: 'Tucuruvi' },
      { name: 'Tumiritinga' },
      { name: 'Tupã' },
      { name: 'Tupaciguara' },
      { name: 'Turf Club' },
      { name: 'Turfe Clube' },
      { name: 'Turiaçu' },
      { name: 'Turvo' },
      { name: 'Tutóia' },
      { name: 'Ubatuba' },
      { name: 'Uberaba' },
      { name: 'Uberaba' },
      { name: 'Ubiratã' },
      { name: 'Ulianópolis' },
      { name: 'Ulisses Guimarães' },
      { name: 'Umarizal' },
      { name: 'Umuarama' },
      { name: 'Una' },
      { name: 'União' },
      { name: 'União' },
      { name: 'Unida de Mogi Guaçu' },
      { name: 'Unida de São Paulo' },
      { name: 'Unida de Suzano' },
      { name: 'Universitário' },
      { name: 'URBIS VI' },
      { name: 'Uruana' },
      { name: 'Uruguaiana' },
      { name: 'Urupá' },
      { name: 'Utinga' },
      { name: 'Vale da Benção' },
      { name: 'Vale das Pedreiras' },
      { name: 'Vale das Pedrinhas' },
      { name: 'Vale de Benção' },
      { name: 'Vale do Jatobá' },
      { name: 'Vale do Sol' },
      { name: 'Vale do Sol' },
      { name: 'Vale dos Lírios' },
      { name: 'Vale dos Reis' },
      { name: 'Vale Encantado' },
      { name: 'Valença' },
      { name: 'Valinhos' },
      { name: 'Valparaíso' },
      { name: 'Vargem Alegre' },
      { name: 'Vargem Alegre' },
      { name: 'Vargem Alta' },
      { name: 'Varginha' },
      { name: 'Varre-Sai' },
      { name: 'Várzea do Poço' },
      { name: 'Várzea Grande' },
      { name: 'Várzea Nova' },
      { name: 'Várzea Paulista' },
      { name: 'Vasco da Gama' },
      { name: 'Vazante' },
      { name: 'Vazante' },
      { name: 'Venda Nova' },
      { name: 'Veneza Tropical' },
      { name: 'Veneza' },
      { name: 'Vera Cruz' },
      { name: 'Verdade e Vida' },
      { name: 'Vespasiano' },
      { name: 'Vicente de Carvalho' },
      { name: 'Vicente Pires' },
      { name: 'Viçosa' },
      { name: 'Vida no Riacho Fundo II' },
      { name: 'Vida Nova' },
      { name: 'Vida' },
      { name: 'Videira' },
      { name: 'Vieira Fazenda' },
      { name: 'Vila Alpes' },
      { name: 'Vila Baronesa' },
      { name: 'Vila Bianchi' },
      { name: 'Vila Bonilha' },
      { name: 'Vila Buenos Aires' },
      { name: 'Vila Concórdia' },
      { name: 'Vila Galli' },
      { name: 'Vila Garrido' },
      { name: 'Vila Geni' },
      { name: 'Vila Guiomard' },
      { name: 'Vila Hortência' },
      { name: 'Vila Industrial' },
      { name: 'Vila Isa' },
      { name: 'Vila Jaguara' },
      { name: 'Vila Jotão' },
      { name: 'Vila Kennedy' },
      { name: 'Vila Madureira' },
      { name: 'Vila Mar' },
      { name: 'Vila Mara' },
      { name: 'Vila Maria' },
      { name: 'Vila Monte Alegre' },
      { name: 'Vila Nilo' },
      { name: 'Vila Norma' },
      { name: 'Vila Nova Galvão' },
      { name: 'Vila Nova' },
      { name: 'Vila Nova' },
      { name: 'Vila Nova' },
      { name: 'Vila Olímpia ' },
      { name: 'Vila Operária' },
      { name: 'Vila Pauline' },
      { name: 'Vila Pavão' },
      { name: 'Vila Permanente' },
      { name: 'Vila Ré' },
      { name: 'Vila Rica' },
      { name: 'Vila Rubens' },
      { name: 'Vila Sotave' },
      { name: 'Vila Telebrasília ' },
      { name: 'Vila Terra Brasil' },
      { name: 'Vilar Carioca' },
      { name: 'Vilar Novo' },
      { name: 'Vinhais' },
      { name: 'Vinhedo' },
      { name: 'Violetas' },
      { name: 'Vista Alegre' },
      { name: 'Vista Alegre' },
      { name: 'Vista da Serra II' },
      { name: 'Vitória da Conquista' },
      { name: 'Vitória de Santo Antão' },
      { name: 'Vitória do Mearim' },
      { name: 'Vitória' },
      { name: 'Viva' },
      { name: 'Volta Redonda' },
      { name: 'Votorantim' },
      { name: 'Votuporanga' },
      { name: 'Wagner' },
      { name: 'Washington Pires' },
      { name: 'Wenceslau Bráz' },
      { name: 'Xanxerê' },
      { name: 'Xinguara' },
      { name: 'Zona Sul' },
    ],
  })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
