# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: IPVE CI

on:
  push:
    branches: [ "v1_dev" ]
  pull_request:
    branches: [ "v1_dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository Code
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
        working-directory: ./front
      - run: npm run lint --fix
        working-directory: ./front
      - run: npm run build 
        working-directory: ./front
      - name: branch-deploy
        uses: github/branch-deploy@v8.2.1
        with:
          # The GitHub token used to create an authenticated client - Provided for you by default!
          github_token: ${{ github.token }}
          # The status of the GitHub Actions - For use in the post run workflow - Provided for you by default!
          status: ${{ job.status }}
          # The name of the default environment to deploy to. Example: by default, if you type `.deploy`, it will assume "production" as the default environment
          environment: production
      
            

      
          
          
                
